//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudynkiMieszkaniaUsterki
    {
        public string opis { get; set; }
        public string stan { get; set; }
        public string adres_budynku { get; set; }
        public int numer { get; set; }
    }
}
