//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mieszkania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mieszkania()
        {
            this.Usterki = new HashSet<Usterki>();
            this.Wynajmy = new HashSet<Wynajmy>();
        }
    
        public int id_mieszkania { get; set; }
        public Nullable<int> id_budynku { get; set; }
        public int numer { get; set; }
        public Nullable<float> metraz { get; set; }
        public string opis { get; set; }
    
        public virtual Budynki Budynki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usterki> Usterki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wynajmy> Wynajmy { get; set; }
    }
}
